# Generated by Django 4.2 on 2025-02-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_delete_author_customuser_bio_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
